### ISSUE TITLE
ShopStake Crashes whenever trying to load blue stake Description

### ISSUE THREAD

**Issue by Italia2407** [encarvlucas/EncarvlucasBalatroMods#1]
Whenever I have the shop stake mod active, and the game tries to load the text for the blue stake (trying to select blue stake for a deck, checking stakes page on blue stake or higher) the game crashes with the folowing screen.
![Screenshot 2024-03-20 203015](https://github.com/encarvlucas/EncarvlucasBalatroMods/assets/28744413/4b680b38-900f-4716-831f-2ad9855280f6)

**Comment by encarvlucas** [comment]
Hello there @Italia2407.
Do you have any other mods? This issue does not seem to happen to me.
<img width="50%" src="https://github.com/encarvlucas/EncarvlucasBalatroMods/assets/30300926/39d04f85-822f-4be5-acbd-15a76094661a" />

**Comment by Italia2407** [comment]
Hello @encarvlucas,
I've had this issue when it was the only mod active.
However after a bit, this issue just solved itself for me as well, not sure what went differently afterwards though.
Thank you very much for your assistance though

**Comment by encarvlucas** [comment]
No problem, glad it got sorted out!
